{
 "title": "NServiceBus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total successful messages ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum without (messaging_type) (rate(nservicebus_messaging_successes_total[5m])*100)"
    }
   ]
  },
  {
   "title": "Average error msg ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(nservicebus_messaging_failures_total[5m])*100"
    }
   ]
  },
  {
   "title": "Messages processed per endpoint",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(nservicebus_messaging_successes_total[5m])*100",
     "legendFormat": "{{nservicebus_message_type}}"
    }
   ]
  },
  {
   "title": "Average msg ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(nservicebus_messaging_successes_total[5m])*100"
    }
   ]
  },
  {
   "title": "Endpoint processed messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nservicebus_messaging_successes_total[5m])*100"
    }
   ]
  },
  {
   "title": "Endpoint fetched messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nservicebus_messaging_fetches_total[5m])*100"
    }
   ]
  },
  {
   "title": "Failed messages",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nservicebus_messaging_failures_total[5m]) * 100"
    }
   ]
  }
 ]
}