

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using NServiceBus;


using OnlineSalesPubSub.Contracts.Marketing;

using OnlineSalesPubSub.Marketing;
	

namespace OnlineSalesPubSub.ECommerce.Controllers
{
    public partial class TestMessagesController : Controller
    {
        //
        // GET: /TestMessages/

        public ActionResult Index()
        {
            return View();
        }

		
	  
        // POST: /TestMessages/SendMessageBrowsedProduct
          
        [HttpPost]
        public string SendMessageBrowsedProduct(BrowsedProduct BrowsedProduct)
        {
            ConfigureBrowsedProduct(BrowsedProduct);
			MvcApplication.Bus.Publish(BrowsedProduct);
            return "<p> BrowsedProduct published</p>";
        }
	  


	  // Send Commands
    
	 // Publish Events
    
        partial void ConfigureBrowsedProduct(BrowsedProduct message);
          }
}
