services:
  docker-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  particular-persistence:
    image: "particular/servicecontrol-ravendb:latest"
    expose:
      - "8080"
    networks:
      - "aspire"
  particular-error:
    image: "particular/servicecontrol:latest"
    command:
      - "--setup-and-run"
    environment:
      RAVENDB_CONNECTIONSTRING: "http://particular-persistence:8080"
      REMOTEINSTANCES: "[{\"api_uri\": \"http://particular-audit:44444\"}]"
      PARTICULARSOFTWARE_LICENSE: "${PARTICULAR_LICENSE}"
      TRANSPORTTYPE: "AmazonSQS"
      CONNECTIONSTRING: "Region=${REGION};AccessKeyId=${ACCESSKEY};SecretAccessKey=${SECRETKEY};QueueNamePrefix=${PREFIX};S3BucketForLargeMessages=${AWSRESOURCES_OUTPUT_LARGEMESSAGEBUCKET};S3KeyPrefix=${PREFIX};"
      SERVICEBUS_ERRORQUEUE: "${AWSRESOURCES_OUTPUT_ERRORQUEUENAME}"
      LICENSINGCOMPONENT_AMAZONSQS_ACCESSKEY: "${ACCESSKEY}"
      LICENSINGCOMPONENT_AMAZONSQS_SECRETKEY: "${SECRETKEY}"
      LICENSINGCOMPONENT_AMAZONSQS_PROFILE: "throughput-profile"
      LICENSINGCOMPONENT_AMAZONSQS_REGION: "${REGION}"
      LICENSINGCOMPONENT_AMAZONSQS_PREFIX: "${PREFIX}"
    expose:
      - "33333"
    depends_on:
      particular-persistence:
        condition: "service_started"
    networks:
      - "aspire"
  particular-monitoring:
    image: "particular/servicecontrol-monitoring:latest"
    command:
      - "--setup-and-run"
    environment:
      PARTICULARSOFTWARE_LICENSE: "${PARTICULAR_LICENSE}"
      TRANSPORTTYPE: "AmazonSQS"
      CONNECTIONSTRING: "Region=${REGION};AccessKeyId=${ACCESSKEY};SecretAccessKey=${SECRETKEY};QueueNamePrefix=${PREFIX};S3BucketForLargeMessages=${AWSRESOURCES_OUTPUT_LARGEMESSAGEBUCKET};S3KeyPrefix=${PREFIX};"
    expose:
      - "33633"
    networks:
      - "aspire"
  particular-audit:
    image: "particular/servicecontrol-audit:latest"
    command:
      - "--setup-and-run"
    environment:
      RAVENDB_CONNECTIONSTRING: "http://particular-persistence:8080"
      PARTICULARSOFTWARE_LICENSE: "${PARTICULAR_LICENSE}"
      TRANSPORTTYPE: "AmazonSQS"
      CONNECTIONSTRING: "Region=${REGION};AccessKeyId=${ACCESSKEY};SecretAccessKey=${SECRETKEY};QueueNamePrefix=${PREFIX};S3BucketForLargeMessages=${AWSRESOURCES_OUTPUT_LARGEMESSAGEBUCKET};S3KeyPrefix=${PREFIX};"
      SERVICEBUS_AUDITQUEUE: "audit"
    expose:
      - "44444"
    depends_on:
      particular-persistence:
        condition: "service_started"
    networks:
      - "aspire"
  particular-servicepulse:
    image: "particular/servicepulse:latest"
    environment:
      SERVICECONTROL_URL: "http://particular-error:33333"
      MONITORING_URL: "http://particular-monitoring:33633"
      PARTICULARSOFTWARE_LICENSE: "${PARTICULAR_LICENSE}"
    expose:
      - "9090"
    networks:
      - "aspire"
  sales:
    image: "${SALES_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      PARTICULARSOFTWARE_LICENSE: "${PARTICULAR_LICENSE}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://docker-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "Sales"
    networks:
      - "aspire"
  clientui:
    image: "${CLIENTUI_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      PARTICULARSOFTWARE_LICENSE: "${PARTICULAR_LICENSE}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://docker-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "ClientUI"
    depends_on:
      sales:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
