

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using NServiceBus;


using OnlineSalesSignalR.Contracts.Sales;

using OnlineSalesSignalR.Sales;
	

namespace OnlineSalesSignalR.ECommerce.Controllers
{
    public partial class TestMessagesController : Controller
    {
        //
        // GET: /TestMessages/

        public ActionResult Index()
        {
            return View();
        }

		
	  
        // POST: /TestMessages/SendMessageOrderAccepted
          
        [HttpPost]
        public string SendMessageOrderAccepted(OrderAccepted OrderAccepted)
        {
            ConfigureOrderAccepted(OrderAccepted);
			MvcApplication.Bus.Publish(OrderAccepted);
            return "<p> OrderAccepted published</p>";
        }
	  


	  // Send Commands
    
	 // Publish Events
    
        partial void ConfigureOrderAccepted(OrderAccepted message);
          }
}
