//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NServiceBus;
using Microsoft.AspNet.SignalR;

namespace OnlineSalesSignalR.Sales
{

	public class BillingCompletedHub : Hub
    {   
    }        
	
}
