apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-saga-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/saga
    type: DirectoryOrCreate

---    
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-transport-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/transport
    type: DirectoryOrCreate