apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-saga-pvc
spec:
  volumeName: host-saga-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests: 
      storage: 1Gi
      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-transport-pvc
spec:
  volumeName: host-transport-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests: 
      storage: 1Gi