version: '3.8'

volumes:

  error:
  audit:
  
services:

  error:
    image: particular/servicecontrol.azureservicebus-windows:4
    ports:
      - 33333:33333
    volumes:
      - error:c:/data
      - ${PROGRAMDATA}/ParticularSoftware:C:/ProgramData/ParticularSoftware
    env_file: environment.env
    restart: unless-stopped

  monitoring:
    image: particular/servicecontrol.azureservicebus.monitoring-windows:4
    ports:
      - 33633:33633
    volumes:
      - ${PROGRAMDATA}/ParticularSoftware:C:/ProgramData/ParticularSoftware
    env_file: environment.env
    restart: unless-stopped

  audit:
    image: particular/servicecontrol.azureservicebus.audit-windows:4
    ports:
      - 44444:44444
    volumes:
      - audit:c:/data
      - ${PROGRAMDATA}/ParticularSoftware:C:/ProgramData/ParticularSoftware
    env_file: environment.env
    restart: unless-stopped

  pulse:
    image: particular/servicepulse-windows:1
    ports:
      - 9090:80
    restart: unless-stopped
