# For more options see https://github.com/devcontainers/images/tree/main/src/dotnet
FROM mcr.microsoft.com/devcontainers/dotnet:10.0-preview

# Required dependency for docstool libskiasharp
RUN sudo apt-get update && sudo apt-get install fontconfig -y

EXPOSE 55666