//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using OnlineSales.Contracts.Billing;


namespace OnlineSales.Sales
{
    public partial class BillingCompletedHandler : IHandleMessages<BillingCompleted>
    {
		
		public void Handle(BillingCompleted message)
		{
			// Handle message on partial class
			this.HandleImplementation(message);
		}

		partial void HandleImplementation(BillingCompleted message);

        public IBus Bus { get; set; }

    }

	
}
