//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using OnlineSales.Internal.Commands.Sales;


namespace OnlineSales.Sales
{
    public partial class SubmitOrderSender : ISubmitOrderSender, ServiceMatrix.Shared.INServiceBusComponent
    {
		
        public void Send(SubmitOrder message)
        {
            ConfigureSubmitOrder(message);
            Bus.Send(message);
        }

        partial void ConfigureSubmitOrder(SubmitOrder message);

        public IBus Bus { get; set; }

    }

	
	public partial interface ISubmitOrderSender
    {
        
        void Send(SubmitOrder message);

	}

	
}
