//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using OnlineSalesPubSub.Contracts.Marketing;


namespace OnlineSalesPubSub.Marketing
{
    public partial class BrowsedProductHandler : IHandleMessages<BrowsedProduct>
    {
		
		public void Handle(BrowsedProduct message)
		{
			// Handle message on partial class
			this.HandleImplementation(message);
		}

		partial void HandleImplementation(BrowsedProduct message);

        public IBus Bus { get; set; }

    }

	
}
