using System;
using System.IO;
using System.Runtime.CompilerServices;

public class SnippetLogger : IDisposable
{
    string outputFilePath;

    public SnippetLogger([CallerFilePath] string sourceFilePath = null, string suffix = "", string version = "")
    {
        string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(sourceFilePath);
        outputFilePath = Path.Combine(Path.GetDirectoryName(sourceFilePath), fileNameWithoutExtension + suffix + ".txt");
        File.Delete(outputFilePath);
        string key = fileNameWithoutExtension;
        string contents = string.Format(
@"Snippet is code generated by {2}
start	code {0}{1} {3}
".Replace("\t", ""), key, suffix, Path.GetFileName(sourceFilePath), version);
        File.AppendAllText(outputFilePath, contents);
    }

    public static void Write(string text, [CallerFilePath] string sourceFilePath = null, string suffix = "", string version = "")
    {
        using (SnippetLogger logger = new SnippetLogger(sourceFilePath, suffix, version))
        {
            logger.WriteLine(text);
        }
    }

    public void WriteLine(string message)
    {
        message = string.Format("{0}\r\n", message);
        File.AppendAllText(outputFilePath, message);
    }

    public void Dispose()
    {
        File.AppendAllText(outputFilePath, "endcode");
    }
}